Made HOMEWORK 2
Artemcor/8-Ball-Without-Actual-Ball pull request #3
Opened 2021-11-08 16:47 UTC by Artemcor

2021-11-08 18:08 UTC, ios-school-yalantis requested changes

2021-11-08 18:08 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeAPIInteractor.swift
> +    }
данная реализация будет блокировать UI пока выполняется запрос, лучше переделать на использование клоужеров

2021-11-08 18:08 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/AppDelegate.swift
>          let controller = navigationController.viewControllers[0] as! ShakeViewController
такой вариант поиска очень не надежный лучше поменять тут на создание класса
что конкретно нужно сделать: написать создание класса кодом, передать в него нужные зависимости и добавить на `window` как корневой контроллер или создать с ним `UINavigationController` и уже его добавить на `window`

2021-11-08 18:39 UTC, Artemcor commented on 8-Ball Without Actual Ball/ShakeAPIInteractor.swift
> +    }
Что имеется ввиду передать на использование клоужеров? Я столкнулся с проблемой что я выхожу с функции раньше чем клоужер фетчит дату и получается, что надо как-то подождать пока выполнится клоужер

2021-11-08 18:43 UTC, Artemcor commented on 8-Ball Without Actual Ball/AppDelegate.swift
>          let controller = navigationController.viewControllers[0] as! ShakeViewController
Имеется ввиду не надежный вариант поиска контроллера, которому я передаю данные в методе func application(...)? И почему он не надежный? Хочу понимать, спасибо

2021-11-09 20:01 UTC, ios-school-yalantis requested changes

2021-11-09 20:01 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/Wireframe.swift
> +        return view
view нужно поменять на controller

2021-11-09 20:01 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeAPIInteractor.swift
> +}
так лучше, но правильно будет использовать completion как аргумент функции getAnswerData, в таком подходе как сделано здесь правильнее будет использовать delegate

2021-11-10 17:36 UTC, ios-school-yalantis approved these changes
все нормально, можно мержить

2021-11-10 20:05 UTC, merged