Home work 3
Artemcor/8-Ball-Without-Actual-Ball pull request #4
Opened 2021-11-12 16:42 UTC by Artemcor

2021-11-13 11:26 UTC, seropusha requested changes
- Думаю стоит разнести файлы по папкам:
 -- Screens/Flows - внутри будут папки с всеми скринами, в будущем будем удобно добавлять, model / viewModel
 -- Resources - сюда засунуть Localizable.strings, Assets, Swiftgen (generated files), Colors.txt, прикольно сделал с сторибоардами (забыл что SwiftGen так умеет)
 
 
 Обратил внимание что у тебя в  AppDelegate хранится лишняя ответственность 
   `var dataModel: AnswerDataModel! ` && `saveData()`
   по вынести нужно эту логику в отдельный объект и добавить NotifactionCenter Obseriving `WillTerminate` && `DidEnterBackground` AppDelegate ничего не должен знать об данных, только стартовать флот и прикидывать ивент в флоу.

2021-11-13 14:12 UTC, Artemcor commented
Поправил вопрос с зависимостью  в AppDelegate
ты не против если я разнесу файлы по папкам в след домашнее, я ее уже начал делать и там как раз отсортировал по папкам? спасибо

2021-11-14 10:11 UTC, seropusha commented
Да хорошо 
не против!

2021-11-14 10:14 UTC, seropusha commented on 8-Ball Without Actual Ball/AppDelegate.swift
> +        NotificationCenter.default.post(name: Notification.Name(rawValue: "SaveNotification"), object: nil)
Уже не актуально как будешь в след домашнее делать
но заметил и скажу 
мы можем подписаться внутри объекта на ивенты UIApplication

`UIApplication.willTerminateNotification`

2021-11-14 18:25 UTC, merged