Feature/homework 4
Artemcor/8-Ball-Without-Actual-Ball pull request #5
Opened 2021-11-15 00:41 UTC by Artemcor

2021-11-16 17:05 UTC, seropusha requested changes
- нужно добавить MVVM для SettingsViewController, экраны должны общаться через их модели, то есть в SettingsViewController не должно быть делегата и в модели лучше реализовать общение через клоужер, будет меньше кода.
- mvvm экраны должны быть вместе, примерно такое древо папок хотелось бы видеть:
-Flows
--Shake
---ShakeModel
---ShakeViewModel
---ShakeViewController
--Settings
---SettingsModel
---SettingsViewModel
---SettingsViewController
-Services
… (all service dependencies here)
-Resources

2021-11-16 17:05 UTC, seropusha commented on 8-Ball Without Actual Ball/ShakeModule/ShakeViewController.swift
> +        DispatchQueue.main.async { [self] in
captured self but not used, в этом кейсе не обязательно кэпчюрить сэлф или делать weak self,  так как клоужер @non-escaping и он обязательно освободится из памяти после выполнения и отпусти все захваченные ссылки.

2021-11-16 17:05 UTC, seropusha commented on 8-Ball Without Actual Ball/Wireframe.swift
>      func start() -> ShakeViewController? {
метод называется start(), а по сути создает контроллер, либо переименовать его в buildShakeViewController()
либо реализовать здесь логику старта, с созданием вью и установкой рутового контроллера.

2021-11-16 17:05 UTC, seropusha commented on 8-Ball Without Actual Ball/ShakeModule/ShakeViewModel.swift
> +            self.answer = result
Ответы должны быть заглавными буквами, не нашел этого.

2021-11-17 13:50 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/SettingsViewModel.swift
> +        settingModel = SettingsModel()
Hidden dependency
use initializer for set this property!

2021-11-17 13:52 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/SettingsModel.swift
> +    var hardcodedAnswers = [Answer]()
if only this file can set value in this property 
use private(set) modifier

2021-11-17 13:55 UTC, ios-school-yalantis approved these changes
Просмотрел оставил пару комментов, принципе все ок.

2021-11-17 13:55 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/SettingsViewModel.swift
> +        settingModel = SettingsModel()
это лучше поправить

2021-11-17 13:55 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/SettingsModel.swift
> +    var hardcodedAnswers = [Answer]()
это лучше поправить

2021-11-17 20:38 UTC, merged