Feature/homework7
Artemcor/8-Ball-Without-Actual-Ball pull request #8
Opened 2021-11-26 21:59 UTC by Artemcor

2021-11-28 12:58 UTC, ios-school-yalantis requested changes
Оставил комменты! Нужна доработка

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/AppDelegate.swift
> +    lazy var managedObjectContext: NSManagedObjectContext = persistentContainer.viewContext
нужно перенести этот код в DB service `managedObjectContext` && `persistentContainer ` 
AppDelegate должен только отправлять ивенты системы (принцип единой отвецтвенности)

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/AppDelegate.swift
> +    func saveContext () {
так же перенести в  DB сервис

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/8BallModel.xcdatamodeld/Model.xcdatamodel/contents
> +</model>
избыточная модель, по сути 2 модели которые делают одно и то же
можно оставить одну `ManagedAnswer` c полями text, date, type, isLocal: Bool

и в случае с аги сохранять isLocal == false
и в случае когда нет интернета фильтровать через предикат по этому полю isLocal == true

так же стоит добавить код который при первом запуске будет записывать все локальные `ManagedAnswer` в базу

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/AppDelegate.swift
> +import CoreData
тут не должно быть импорта кор даты

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/Model/ManagedAnswer.swift
>      var type = ""
лучше сделать их let  так как они не должны менятся, так мы избавим себя от будущих проблем вдруг кто то изменит, а потом ищи в чем проблема :)

если будут let то нужно убрать присвоение `= ""` и использовать только инциализатор

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/Resources/SecureStorageKey.swift
> +    case shakeCouner
typo "shakeCounter"

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/DBService.swift
> +    func loadLocalsAnswers() -> [LocalDBAnswer] {
если будет 1 модель стоит избавится от метода, 

так же можно сделать дженерик private метод который будет вытаскивать все по реквесту
```
    private func getObjects<T: NSManagedObject>(
        _ request: NSFetchRequest<T>,
        completion: @escaping (Result<[T]>) -> Void
    ) {
        let context = yourContext
        context.perform {
            do {
                let result = try context.fetch(request) as! [T]
                completion(.success(result))
            } catch let error {
                completion(.failure(error))
            }
       
``` 

а публичный будет формировать реквест и возвращать уже нужные объекты, меньше кода меньше ошибок!

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/DBService.swift
> +    init(context: NSManagedObjectContext) {
контекст должен создаваться внутри сервиса

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/History/HistoryModel.swift
> +            let answer = HistoryAnswer(answer: dbAnswer.answer, date: dbAnswer.date)
нужно написать экстеншн на `ManagedAnswer` в него добавить метод `toAnwer()` в котором будет происходит трансформация в твою структуру и использовать его,  таки образом избежим кейса когда добавится новое поле в модель и прийдется по всему коду его добавлять

так же можно использовать не `for` loop, а `dbAnswers.map { $0. toAnwer()}` map - это метод преобразования, пройдется по всем элементам массива и вернет новый массив с новыми объектами.

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/History/HistoryViewController.swift
> +    private var historyAnswers = [HistoryAnswer]()
котроллер ничего не должен знать об данных
все должно быть в модели и через вьюМодел контроллер может запросить их

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/History/HistoryViewController.swift
> +        return historyAnswers.count
use viewModel

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/History/HistoryViewController.swift
> +        let answer = historyAnswers[indexPath.row]
use viewModel

2021-11-28 12:58 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/Wireframe.swift
> +        let dbService = DBService(context: managedObjcetContext)
в кейсе когда внутри `DBService` будет инкапсулированы `context` && `StoreContainer` для каждого инстанса `DBService` они буду свои, это ведет к тому что, все модели контроллеров должны быть созданы с одним и тем же инстансом `DBService`.

Иначе может быть кейс когда добавишь объекты в одном контексте, и сохранишь на другом экране (совсем в другом контексте) и объекты не добавятся в стор. Что бы этого избежать нужно юзать 1 инстанс `DBService`.

и не делай его синглтоном, просто создай его внутри WireFrame и прокинь во все модели.

2021-11-28 23:10 UTC, Artemcor commented on 8-Ball Without Actual Ball/ShakeModule/DBService.swift
> +    func loadLocalsAnswers() -> [LocalDBAnswer] {
вот с этим мне нужно разобраться, как это работает. это круто, спасибо)

2021-11-29 00:47 UTC, Artemcor commented
Появилась такая ошибка после моих исправлений, ошибка вылазит когда многократно сохраняю локальных ответы и потом шейкаю телефон без интернета соответственно фетчиться локальные ответы и через несколько раз вылазит такая ошибка, когда вызывается context.save(). Попробовал все команды что касается кордаты обернуть в Dispatchqueue.main подумал, что это может из за того что на беграунд очереди вызываю метод LOAD из coredata но не помогло(

Thread 1: Fatal error: Unresolved error Error Domain=NSCocoaErrorDomain Code=134020 "The model configuration used to open the store is incompatible with the one that was used to create the store." UserInfo={NSAffectedObjectsErrorKey=<DBManagedAnswer: 0x106c4b4b0> (entity: DBManagedAnswer; id: 0x1056b2500 <x-coredata:///DBManagedAnswer/t8DCAFAE0-1065-45E3-8102-6B38795EAB3D41>; data: {
    answer = "DON'T EVEN THINK ABOUT IT!";
    date = "2021-11-29 00:36:39 +0000";
    isLocal = 0;
    type = Contrary;
})}, ["NSAffe

2021-11-29 10:59 UTC, Artemcor commented
этот эктеншин решил данную проблему. правда до конца не понял в чем суть 
public extension NSManagedObject {

    convenience init(context: NSManagedObjectContext) {
        let name = String(describing: type(of: self))
        let entity = NSEntityDescription.entity(forEntityName: name, in: context)!
        self.init(entity: entity, insertInto: context)
    }

}

2021-11-29 11:12 UTC, ios-school-yalantis approved these changes
Нужно разбираться так сразу и скажу в чем проблема, 
пробовал удалить и сблизить заново, ошибка повторяется? 

так в общем посмотрел, выглядит хорошо, поправь последние комменты плз, если не получится разобраться с крашем постараюсь помочь позже! И Гугл в помощь)

2021-11-29 11:12 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/Model/AnswerModel.swift
> +    var type: String
change var -> let

2021-11-29 11:12 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/Model/PresentableAnswer.swift
> +    var type: String
var -> let

2021-11-29 11:12 UTC, ios-school-yalantis commented on 8-Ball Without Actual Ball/ShakeModule/DBService.swift
> +    lazy var persistentContainer: NSPersistentContainer = {
make it private

2021-11-29 12:28 UTC, merged